### ISSUE TITLE
Bug: `Election.get_race_objects()` fails with initialization data

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-ap-elections#40]
```======================================================================
ERROR: test_json_shape (tests.test_race.TestRaceInitialization)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/jbowers/src/nyt/nyt-ap-elections/tests/test_race.py", line 70, in setUp
    self.race_objs = e.get_race_objects(self.raw_races)
  File "/Users/jbowers/src/nyt/nyt-ap-elections/elex/parser/api.py", line 412, in get_race_objects
    payload.append(Race(**r))
  File "/Users/jbowers/src/nyt/nyt-ap-elections/elex/parser/api.py", line 290, in __init__
    self.set_candidates()
  File "/Users/jbowers/src/nyt/nyt-ap-elections/elex/parser/api.py", line 81, in set_candidates
    candidate_dict['statename'] = STATE_ABBR[getattr(self, 'statepostal')]
AttributeError: 'Race' object has no attribute 'statepostal'

----------------------------------------------------------------------
```

**Comment by jeremyjbowers** [comment]
Fixed. Issue with statename / statepostal getting set at different times in the initialization and liveresults versions of the data.
