### ISSUE TITLE
new-elections fails when pip installed

### ISSUE THREAD

**Issue by jeremyjbowers** [newsdev/nyt-ap-elections#77]
```
2015-11-17 13:22:20,622 (INFO) elex : Getting next election
Traceback (most recent call last):
  File "/Users/jbowers/.virtualenvs/fakelections/bin/elex", line 9, in <module>
    load_entry_point('nyt-ap-elections==0.0.35', 'console_scripts', 'elex')()
  File "/Users/jbowers/.virtualenvs/fakelections/src/nyt-ap-elections/elex/cli/app.py", line 145, in main
    app.run()
  File "/Users/jbowers/.virtualenvs/fakelections/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/Users/jbowers/.virtualenvs/fakelections/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/jbowers/.virtualenvs/fakelections/src/nyt-ap-elections/elex/cli/app.py", line 120, in next_election
    election = self.app.election.get_next_election()
  File "/Users/jbowers/.virtualenvs/fakelections/src/nyt-ap-elections/elex/parser/api.py", line 475, in get_next_election
    for e in Election.get_elections():
  File "/Users/jbowers/.virtualenvs/fakelections/src/nyt-ap-elections/elex/parser/api.py", line 468, in get_elections
    return [Election(**election) for election in list(utils.api_request('/')['elections'])]
KeyError: 'elections'
```

**Comment by eads** [comment]
hmmm... that seems like something is going wrong at the AP API layer. Do you have the env var set?

**Comment by jeremyjbowers** [comment]
Got this sorted in #88.
