### ISSUE TITLE
elex races fails

### ISSUE THREAD

**Issue by wmandrews** [newsdev/nyt-ap-elections#89]
```
elex races $RACEDATE
2015-11-18 17:12:16,144 (INFO) elex : Getting races for election 2015-11-03
Traceback (most recent call last):
  File "/Users/wilson/.virtualenvs/elextest/bin/elex", line 9, in <module>
    load_entry_point('nyt-ap-elections==0.0.35', 'console_scripts', 'elex')()
  File "/Users/wilson/.virtualenvs/elextest/src/nyt-ap-elections/elex/cli/app.py", line 145, in main
    app.run()
  File "/Users/wilson/.virtualenvs/elextest/lib/python2.7/site-packages/cement/core/foundation.py", line 764, in run
    self.controller._dispatch()
  File "/Users/wilson/.virtualenvs/elextest/lib/python2.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/Users/wilson/.virtualenvs/elextest/src/nyt-ap-elections/elex/cli/decorators.py", line 13, in decorated
    return fn(self)
  File "/Users/wilson/.virtualenvs/elextest/src/nyt-ap-elections/elex/cli/app.py", line 53, in races
    self.app.render(self.app.election.races)
  File "/Users/wilson/.virtualenvs/elextest/src/nyt-ap-elections/elex/parser/api.py", line 612, in races
    test=self.testresults
  File "/Users/wilson/.virtualenvs/elextest/src/nyt-ap-elections/elex/parser/api.py", line 553, in get_raw_races
    self.next_request = payload['nextrequest']
KeyError: 'nextrequest'
```

**Comment by eads** [comment]
Is this with the latest pypi version? 

This seems likely to be either an issue with the API key (probably not, but it could be) or with an undefined $RACEDATE variable (seems more likely). 

If $RACEDATE isn't defined, the latest dev version returns:

```
Please specify an election date (e.g. `elex races 2015-11-03`) or data file (e.g. `elex races --data-file path/to/file.json`).

Run `elex` for help.
```
